name: Workflow push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Mise en cache des dépendances
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-package-${{ hashFiles('**/package-lock.json') }}

      - name: Installation des dépendances
        run: mvn install

      - name: Build de l'application
        run: mvn package

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Récupération de l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: mon_app